# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./thumbnails:/app/thumbnails
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: python app.py
    
  # For development with auto-reload
  dev:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py

volumes:
  downloads:
  thumbnails: